name: Build and Deploy FastAPI

on:
  push:
    branches:
      - main
      - dev
      - feature/*
      - bugfix/*
      - hotfix/*
      - release/*
      - support/*
      - refactor/*
      - chore/*
      - docs/*
  pull_request:
    branches:
      - main
      - dev
      - feature/*
      - bugfix/*
      - hotfix/*
      - release/*
      - support/*
      - refactor/*
      - chore/*
      - docs/*

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
